In [1]:
import pandas as pd



In [3]:
!pip install PyPDF2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 3.5 MB/s eta 0:00:00


In [4]:
import PyPDF2

def extract_text_from_pdf(pdf_file):
    text = ""
    with open(pdf_file, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            text += page.extract_text()
    return text

In [6]:
text=extract_text_from_pdf('/content/200040010-1 (1).pdf')

In [8]:
print(text)

Think9
|
Machine
Learning
Research
Internship
[Jul’23-Aug’23] 
Received
Letter
of
Recommendation
from
the
Founder
for
Exemplary
performance
during
the
Internship 
●
Built
a
machine
learning
model
to
predict
sales
of
the
“Kingdom
of
White”
D2C
clothing
brand 
●
Collaborated
with
Marketing
and
Business
Analytics
Team
to
get
insight
on
customer
acquisition
plane 
●
utilized
advanced
techniques
such
as
ARIMA,
SARIMA,
Prophet,
Random
Forest,
Neural
Networks,
and 
Machine
Learning
Regression
Algorithms,
with
Prophet
method
yielding
the
best
results
among
all 
Education
Technology
|
Summer
Under graduate
Research
Internship
(SURI)
[May’23-Jul’23] 
●
Utilized
OpenCV
to
extract
frames
and
applied
VGG16
(Transfer
Learning)
to
extract
features
from
video 
●
Selected
optimal
number
of
clusters
for
K-means
clustering
of
images
using
elbow
plot
and
silhouette
score 
●
Utilized
Late
fusion
technique
and
XGBoost
to
achieve
75%
accuracy
in
predicting
assignment
correctness
Car
Parking
Space
counter
|
S

In [10]:
arr=text.split('●')

In [11]:
arr[0]

'Think9\n|\nMachine\nLearning\nResearch\nInternship\n[Jul’23-Aug’23] \nReceived\nLetter\nof\nRecommendation\nfrom\nthe\nFounder\nfor\nExemplary\nperformance\nduring\nthe\nInternship \n'

In [12]:
!pip install -U sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 18.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 41.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 15.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 51.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 67.3 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125924 sha256=9d02e285fd9d1bf5e7cffdc2c36eda5e4a20574c9804edc0d476c73e63f8242a
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


In [19]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')



In [14]:
model.encode('apple')

array([ 6.41589642e-01, -2.10146800e-01,  5.88113487e-01,  4.29269262e-02,
        3.54805678e-01,  2.07127497e-01,  2.61196822e-01, -3.17229144e-02,
        4.58385563e-03, -9.21461657e-02,  6.01072848e-01, -4.69213963e-01,
       -8.05742204e-01,  3.55321288e-01, -3.94557863e-01, -2.74195045e-01,
       -3.41489911e-01, -4.07279253e-01, -2.70377785e-01,  1.67918861e-01,
        6.07746720e-01, -4.90861893e-01, -1.70636773e-01, -3.24900419e-01,
       -1.41822383e-01,  6.06484234e-01,  1.09012716e-01, -1.32442147e-01,
        1.91313419e-02, -5.05031526e-01,  4.59870577e-01, -3.08082998e-01,
        1.02057636e+00,  3.92195225e-01, -8.16718787e-02, -2.72221625e-01,
        1.39353886e-01, -6.87885523e-01,  1.76665783e-02, -9.50143635e-02,
        4.94362265e-02,  5.11186242e-01, -3.48881632e-01,  4.13915724e-01,
        5.01203358e-01,  5.76039851e-01,  2.48004809e-01, -7.49632657e-01,
        2.40350842e-01, -1.06810428e-01,  9.44852829e-02,  1.98306575e-01,
        8.25102150e-01, -

In [15]:
!pip install -q utils

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
cosine_similarity(model.encode('apple').reshape(-1,1),model.encode('pineapple').reshape(-1,1))

array([[-1., -1., -1., ..., -1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1., -1., -1.],
       [-1., -1., -1., ..., -1.,  1.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1., -1., -1.],
       [-1., -1., -1., ..., -1.,  1.,  1.],
       [-1., -1., -1., ..., -1.,  1.,  1.]], dtype=float32)

In [20]:
util.cos_sim(model.encode('apple'),model.encode('mango'))

tensor([[0.4787]])

In [27]:
util.cos_sim(model.encode('I am good boy '),model.encode('I am not good boy'))

tensor([[0.7417]])

In [32]:
cos=[util.cos_sim(model.encode('what is think9'),i) for i in list(map(model.encode,arr))]

In [33]:
import numpy as np

In [38]:
cos=[i.item() for i in cos]

In [37]:
cos[0].item()

0.2991943359375

In [40]:
max(cos)

0.2991943359375

In [41]:
cos.index(max(cos))

0

In [44]:
def sementic_chunk(query):
  cos=[util.cos_sim(model.encode(query),i) for i in list(map(model.encode,arr))]
  cos=[i.item() for i in cos]
  return arr[cos.index(max(cos))]

In [46]:
print(sementic_chunk('what is machine learning'))


utilized
advanced
techniques
such
as
ARIMA,
SARIMA,
Prophet,
Random
Forest,
Neural
Networks,
and 
Machine
Learning
Regression
Algorithms,
with
Prophet
method
yielding
the
best
results
among
all 
Education
Technology
|
Summer
Under graduate
Research
Internship
(SURI)
[May’23-Jul’23] 

